### ISSUE TITLE
Dynamic <ui:include> duplicates a composite component

### ISSUE THREAD

**Issue by javaserverfaces** [javaserverfaces/mojarra#3944]
I am trying to modify the component tree by changing an included facelet in an action listener (invoke application phase). The newly included facelet contains a composite component. An instance of that component also exists elsewhere in the tree. Dynamic include affects somehow that other (not included) composite component instance and its contents get duplicated. This causes an java.lang.IllegalStateException: Component ID notIncluded:outputText has already been found in the view.
#### Environment
Wildfly 8.2
#### Affected Versions
[2.2.8]

**Comment by xinyuan-zhang** [comment]
Closed, Duplicate Bug. Same to Duplicate ID exception when using composite component with c:if #4244
