### ISSUE TITLE
Using c:if: Component ID * has already been found in the view

### ISSUE THREAD

**Issue by javaserverfaces** [javaserverfaces/mojarra#3982]
Since updating to Mojarra 2.2.8 and Glassfish 4.1 we are experiencing issues with composite components in combination with c:if.

We have a component in a c:if that is currently not rendered, and we enable it with a commandLink (see example). After the commandLink is clicked we receive the following error:

javax.servlet.ServletException: Component ID form:panel2:panelTest has already been found in the view.

We did not experience these issues with Glassfish 3.1.2 and Mojarra 3.1.20.

I have attached an example war file that will demonstrate the problem.

example.xhtml

```
<h:form id="form">
	<c:if test="#{not bean.clicked}" id="test">            
		<test:inputPanel id="panel1" labelText="test" value="#{bean.arrival}"/>
	</c:if>
	<test:inputPanel id="panel2" labelText="test" value="#{bean.emailAgain}"/>  
	<h:commandLink value="Click" action="#{bean.click}" />
</h:form>
```

Component

```
<!-- INTERFACE -->
<cc:interface>
	<cc:attribute name="labelText" required="false" shortDescription="Label of element"/>
	<cc:attribute name="id" required="false"/>
	<cc:attribute name="value" required="true"/>
</cc:interface>

<!-- IMPLEMENTATION -->
<cc:implementation id="#{cc.attrs.id}">
	<h:panelGrid cellpadding="0" cellspacing="0" columns="2" width="100%" id="panelTest">
		<h:outputText value="#{cc.attrs.labelText}"/>
		<h:inputText value="#{cc.attrs.value}" />
	</h:panelGrid>
</cc:implementation>
```
#### Environment
Glassfish 4.1
#### Affected Versions
[2.2.8, 2.2.11, 2.3.0-m02]

**Comment by xinyuan-zhang** [comment]
Closed, Duplicate Bug. Same to Duplicate ID exception when using composite component with c:if #4244
