### ISSUE TITLE
DelegatingAnnotationProvider does not handle ArrrayStoreException when retrieving annotations

### ISSUE THREAD

**Issue by javaserverfaces** [javaserverfaces/mojarra#4080]
When retrieving a class's annotations via getAnnotations, an ArrayStoreException can be thrown if the class is annotated with an annotation that references a class that isn't on the classpath. One such example is Spring Boot's ConditionalOnBean annotation whose value is a Class[]. A specific example of this problem is [described in this Spring Boot issue](https://github.com/spring-projects/spring-boot/issues/4321#issuecomment-151782768).

DelegatingAnnotationProvider currently catches any NoClassDefFoundError thrown while retrieving a class's annotation but doesn't deal with the above-described possibility of an ArrayStoreException being thrown.
#### Affected Versions
[2.2.12]

**Comment by xinyuan-zhang** [comment]
Closed as the related spring boot issue was closed.
