### ISSUE TITLE
ui:repeat varStatus last properties error when there is an offset

### ISSUE THREAD

**Issue by javaserverfaces** [javaserverfaces/mojarra#4098]
In UIRepeat.process(), when iterating on a list on n elements with an offset of n-1, the IterationStatus is not initialize correctly.
The last property is set to false, but it should be set to true as it is the first and last element.

The initialization should be :
<tt>this.updateIterationStatus(faces, new IterationStatus(true, (i + s >= e), i, begin, end, step));</tt>
#### Environment
windows, linux,...
#### Affected Versions
[2.2.12]

**Comment by xinyuan-zhang** [comment]
Closed, Could Not Reproduce
