### ISSUE TITLE
[PORT 2.2.8]The parameter is not passed to h:commandButton defined as composite component

### ISSUE THREAD

**Issue by javaserverfaces** [javaserverfaces/mojarra#4102]
The parameter is not passed to h:commandButton defined as composite component.
Please take a look at the example.

1\. Deploy the testapp.war
2\. Access to [http://localhost:8080/testapp/test.xhtml](http://localhost:8080/testapp/test.xhtml)
3\. Push the "Hello World" button.
4\. You can confirm following output on stdout.

```
# called initialize()
# called button2() value=
# called initialize()
```

But, TomEE/MyFaces is able to output "Hello World" as follows.

```
# called initialize()
# called button2() value=Hello World
# called initialize()
```
#### Affected Versions
[2.1.28, 2.2.7]

**Comment by xinyuan-zhang** [comment]
applied to 2.2.8: e8bd4033d20dcc2a54d8fda37ec95e23043eec2d

[port 2.2.x] JAVASERVERFACES-4073
#4103
The parameter is not passed to h:commandButton defined as composite component

modified:   jsf-ri/src/main/java/com/sun/faces/application/view/FaceletViewHandlingStrategy.java
new file:   test/javaee6web/facelets/src/main/java/com/sun/faces/test/javaee6web/facelets/Issue4073Bean.java
new file:   test/javaee6web/facelets/src/main/webapp/WEB-INF/template/template.xhtml
new file:   test/javaee6web/facelets/src/main/webapp/WEB-INF/xhtml/parts.xhtml
new file:   test/javaee6web/facelets/src/main/webapp/issue4073.xhtml
new file:   test/javaee6web/facelets/src/main/webapp/resources/t/comp.xhtml
new file:   test/javaee6web/facelets/src/test/java/com/sun/faces/test/javaee6web/facelets/Issue4073IT.java
