### ISSUE TITLE
Incorrect XML parsing of facelet source. Produces invalid markup

### ISSUE THREAD

**Issue by javaserverfaces** [javaserverfaces/mojarra#4185]
I am trying to output XML markup from JSF.

The original markup is generated by MSOffice 2003\. Then I try to output this plain XML from Faces. I paste XML in Facelet page.

I have got incorrect markup from JSF which based on correct XML in Facelet source. Some of XML TAGS are skipped or in incorrect place.

The main problem is in namespaces of source XML.
#### Environment
Tomcat 8 Windows 7
#### Affected Versions
[2.2.11]

**Comment by xinyuan-zhang** [comment]
Closed, Could Not Reproduce
