### ISSUE TITLE
UIRepeat wrong state restored for UIInput

### ISSUE THREAD

**Issue by javaserverfaces** [javaserverfaces/mojarra#4206]
The components p:outputLabel and h:inputText (same with p:inputText) are inside an ui:repeat. As long as no validation failes for the inputText everything is fine.

As soon as the validation failes, only the failed inputText is marked invalid, all other fields are in the corret state and show the correct (submitted) value. If the value is corrected so that the validation succeeds again, all input field will get the state from the latest iterations inputText. The wrong state is applied during RENDER_RESPONSE phase.

The wrong state doesn't affect the request processing (validation-phase and apply-phase are passed successfully). E.g. actionListener is invoked. Only the GUI is wrong, as the outputLabel (and p:inputText - if used) indicate isValid=false.

I'm sorry that I currently cannot provide an example WAR.

```
**StackTrace (extract)**HtmlInputText(UIInput).setValid(boolean) line: 456	
UIRepeat$SavedState.apply(EditableValueHolder) line: 959	
UIRepeat.restoreChildState(FacesContext, UIComponent) line: 431	
UIRepeat.restoreChildState(FacesContext) line: 415	
UIRepeat.setIndex(FacesContext, int) line: 546	
UIRepeat.process(FacesContext, PhaseId) line: 615	
UIRepeat.encodeChildren(FacesContext) line: 1116
```
```
<ui:repeat value="#{bean.entryList}" var="entry" varStatus="state">
  <p:outputLabel value="#{state.index + 1}" for="itPermissionName"  />
  <h:inputText value="#{entry.name}" id="itPermissionName" required="true" />
</ui:repeat>
```
#### Environment
Wildfly 10.1
#### Affected Versions
[2.2.13]

**Comment by xinyuan-zhang** [comment]
Closed, Duplicate Bug. Same to ui:repeat child state saving depends on the source of the request #4247
