### ISSUE TITLE
h:inputText doesn't update it's 'value' attribute when updates applied to it

### ISSUE THREAD

**Issue by javaserverfaces** [javaserverfaces/mojarra#4248]
While implementing own paginator for datatable and switching between pages with SAME number of rows the update is applied strictly on each table cell element i.e.:
[window] [Wed, 26 Apr 2017 13:01:09 GMT] applied updates >>
update["form:table:0:input"]: <input id="form:table:0:input" name="for....
This leads to incorrect state of h:inputText 'value' attribute which would be initial one. Real, live value is changed either way which is correct. Both can be found/observed:

*   document.getElementById("form:table:0:input") -> incorrect
*   document.getElementById("form:table:0:input").value -> correct

The 'value' attribute would be changed only when number of rows would change, which triggers entire table update:
[window] [Wed, 26 Apr 2017 13:14:04 GMT] applied updates >>
update["form:table"]: <table id="form:table">
This behavior is not applied to other components like h:commandButton, h:outputText or h:inputTextarea which are generated in html correctly.

Classes needed to reproduce this behavior attached below (tested also on x2.2.14):

>>> BEAN >>> HtmlTableTestJsf.java

@ManagedBean(name = "htmlTableTestJsf")
@ViewScoped
public class HtmlTableTestJsf implements Serializable {
private static final long serialVersionUID = 1L;
private final List<NameBean> names;
private int pageSize = 2;
private int currentPage = 0;
public HtmlTableTestJsf() {
names = new LinkedList<NameBean>();
for (int i = 1; i < 10; i++)

{ String name = "NAME_" + i; names.add(new NameBean(name)); }

}
public List<NameBean> getNames()

{ return names; }

public List<NameBean> getPageRows()

{ int startingIndex = (currentPage * pageSize); int endingIndex = (startingIndex + pageSize) > names.size() ? names.size() : startingIndex + pageSize; List<NameBean> pageRows = new ArrayList<>(names.subList(startingIndex, endingIndex)); return pageRows; }

public String nextPage()

{ currentPage = (names.size() / pageSize) >= currentPage + 1 && (names.size() % pageSize) > 0 ? currentPage + 1 : currentPage; return null; }

public String prevPage()

{ currentPage = (currentPage - 1 < 0) ? 0 : currentPage - 1; return null; }

}

>>> VIEW >>> htmlTableTestJsf.xhtml

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
xmlns:h="http://java.sun.com/jsf/html">
<h:head>
<title>DataTable JSF custom Pager</title>
</h:head>
<h:body>
<h:form id="form">
<h:dataTable id="table" value="#

{htmlTableTestJsf.pageRows}

" var="row" rows="2">
<h:column id="col_input" >
<h:inputText id="input" value="#

{row.name}" />
</h:column>
<h:column id="col_button" >
<h:commandButton id="button" action="act();" value="#{row.name}

" />
</h:column>
<h:column id="col_output" >
<h:outputText id="output" value="#

{row.name}" />
</h:column>
<h:column id="col_area" >
<h:inputTextarea id="area" value="#{row.name}

" />
</h:column>
</h:dataTable>
<h:commandButton id="prevPage" type="submit" value="-" action="#

{htmlTableTestJsf.prevPage}

" />
<h:commandButton id="nextPage" type="submit" value="+" action="#

{htmlTableTestJsf.nextPage}

" />
</h:form>
</h:body>
</html>
#### Affected Versions
[2.1.29-01]

**Comment by xinyuan-zhang** [comment]
Closed, Could Not Reproduce
