### ISSUE TITLE
Download link on https://javaserverfaces.github.io/ is broken

### ISSUE THREAD

**Issue by kito99** [javaserverfaces/mojarra#4250]
I would submit a pull request but I have no idea where the proper download link for old binaries is...

The link on https://javaserverfaces.github.io/users.html is incorrect as well...

**Comment by ngriffin7a** [comment]
FYI, just wanted to mention that downloads are also listed on the Spec level page: https://javaee.github.io/javaserverfaces-spec/

**Comment by arjantijms** [comment]
Hi,

A chronic lack of time prevented me to look at the Mojarra homepage
earlier, but should do it soon. There's a couple of more errors, and
everything seems to have gone back a couple of revisions as well :(

I hope to take a look at it tomorrow.

Thanks!

Kind regards,
Arjan Tijms

**Comment by kito99** [comment]
Thanks Neil.

**Comment by edburns** [comment]
I fixed the link on the users.html page.

**Comment by edburns** [comment]
Fixed this, but clearly a more complete broken link traversal is necessary.
