### ISSUE TITLE
Remove context-param to enable HTTP/2 server push

### ISSUE THREAD

**Issue by edburns** [javaserverfaces/mojarra#4253]
This must not be behind a context-param, to achieve compliance with the new text in JSF 2.3 spec section 2.2.6.

**Comment by arjantijms** [comment]
+1

**Comment by edburns** [comment]
Let's see how this goes with our CI.

**Comment by deki** [comment]
Can you please fix the release notes? The contents references this issue and the artifactId is also correct but in the title it is named 2.2.8: https://github.com/javaserverfaces/mojarra/releases
