### ISSUE TITLE
Is CDI mandatory for JSF 2.3?

### ISSUE THREAD

**Issue by zsalab** [javaserverfaces/mojarra#4268]
The ELUtils throws an exception with JSF 2.3 if no CDI BeanManager present
https://github.com/javaserverfaces/mojarra/blob/master/impl/src/main/java/com/sun/faces/el/ELUtils.java:312
                throw new FacesException("Unable to find CDI BeanManager");

Is CDI mandatory for JSF 2.3?

**Comment by arjantijms** [comment]
Yes, CDI is mandatory indeed for JSF 2.3. For JSF 2.2 it was somewhat mandatory, as certain features (e.g. flow scope) would not work without it.

**Comment by zsalab** [comment]
sad, I can not use JSF any further :(
Thank you for your answer

**Comment by arjantijms** [comment]
No worries, note btw that you can add CDI separately to Tomcat etc.

**Comment by zsalab** [comment]
I am using spring, and I really do not want to change, looks tomcat get crazy if I add weld and jetty just did not start..... so probably the best if I give up JSF at all

**Comment by arjantijms** [comment]
Tomcat normally just works with Weld, we test OmniFaces with it all the time. See this one for some instructions; http://balusc.omnifaces.org/2013/10/how-to-install-cdi-in-tomcat.html

**Comment by ngriffin7a** [comment]
@arjantijms Is there anything in the JSF Spec or that would require a compliant JSF 2.3 implementation to require CDI? If not, couldn't Mojarra 2.3 be more like Mojarra 2.2? For example, `@FlowScoped` doesn't work unless CDI is present, but CDI is not required for most all other JSF 2.2 features. Another example -- in the case of the MBF, I realize that it has been deprecated, but it seems like it should continue to work without something like the cdi-api.jar and weld-servlet.jar being added to tomcat/lib.

**Comment by arjantijms** [comment]
@ngriffin7a JSF 2.3 made many additional steps to rebase on CDI, so many new things (including some core things) now require CDI. 

Without CDI, few things would be left that are of interest in JSF 2.3, and perhaps the user would then be better of continuing to use JSF 2.2. For instance, the WebSocket integration requires CDI as well (in addition to, perhaps obviously, WebSocket).

The MBF however still works. It's only marked deprecated, but has not been pruned or made optional in this release. Perhaps it would make sense though to additionally log warning messages (that can be disabled) if JSF native managed beans are used.

**Comment by ngriffin7a** [comment]
@arjantijms JSF 2.3 is definitely a compelling upgrade for CDI users and for those that need `f:websocket`, but other features in JSF 2.3 such as JAVASERVERFACES_SPEC_PUBLIC issues 1, 217, 329, 613, 790, 936, 1078, 1102, 1103, 1007, 1135, 1238, 1260, 1355, 1364, 1370, 1382, 1396, 1404, 1412, 1422, 1423, 1424, 1428, 1429, 1434, and 1435 are also very attractive. I get the impression that are many legacy applications that use the MBF or Spring that could benefit from these new features. Also, is my best understanding that the MBF is also very much used in portlets. Another compelling reason to upgrade from Mojarra 2.2 to Mojarra 2.3 is to take advantage of the latest bug fixes, which don't always get backported to older branches. Finally, the backport branches are typically on a slower release schedule.

**Comment by ngriffin7a** [comment]
@arjantijms Also wanted to mention that the new Portlet 3.0 Specification has many new features that rely on CDI, but the spec is written in such a way as to use language like "If CDI is present, then..." for CDI-specific features.

**Comment by arjantijms** [comment]
@ngriffin7a I hear you, and some of that was discussed earlier, but I think the consensus of sort was to not abstract from CDI, but let CDI be essentially the foundation of JSF, and then should users want to integrate other bean models then CDI bridges can be created for those (not totally unlike your Portlet bridge ;)).

CDI should be quite flexible there, and both dynamic bean building (see e.g. https://github.com/javaee-samples/javaee8-samples/blob/master/cdi/dynamic-bean/src/main/java/org/javaee8/cdi/dynamic/bean/CdiExtension.java#L16) as well as producers can be used to bridge any gap.

The MBF doesn't really need such bridge though, as it remains fully active. Nothing has been changed really except for marking it as deprecated via an annotation and javadoc.

To fully take advantage of CDI and firmly establish it as a binding foundation for all EE specs, I think the "CDI first" approach is the best way forward. Indeed, in JSF 2.0 it was implicitly (non-spec) "If CDI is present, then...", and then in JSF 2.2 it was "for some features CDI MUST be present", and now with JSF 2.3 it's "for more features CDI MUST be present and the RI does not try to accommodate for non-CDI environments, plus the BMF is deprecated (but still fully present)"

I have to double check but I think the JSF 2.3 spec also mentions that CDI must be present (just as that JDK 8 must be present, JSF 2.3 does not try to be compatible with JDK 7 and earlier anymore, which likely a lot of legacy applications are using as well).

**Comment by arjantijms** [comment]
p.s. some of the above is also because of pragmatic reasons; as you know the resources available to JSF are not that much. When a concern was raised for WebSocket requiring CDI, with some people still on e.g. Java EE 5, but still wanting to upgrade to JSF 2.3, it was offered for those interested in that to donate a non-CDI dependent WebSocket version, but such donation was never done.

Only having CDI support in core JSF without taking into account alternative bean models is much simpler to implement and much simpler to spec.
