### ISSUE TITLE
HtmlResponseWriter breaks conditional comments

### ISSUE THREAD

**Issue by Toberumono** [javaserverfaces/mojarra#4288]
HtmlResponseWriter encodes the contents of HTML comments.
For example:
```xhtml
<f:view ...>
  <!--[if lt IE 9 ]><html class="ltIE9" xmlns="http://www.w3.org/1999/xhtml"><![endif]-->
  <!--[if IE 9 ]><html class="IE9" xmlns="http://www.w3.org/1999/xhtml"><![endif]-->
  <!--[if !IE]><!--><html xmlns="http://www.w3.org/1999/xhtml"><!--<![endif]-->
</f:view>
```

The expected output is:
```html
<!--[if lt IE 9 ]><html class="ltIE9" xmlns="http://www.w3.org/1999/xhtml"><![endif]-->
<!--[if IE 9 ]><html class="IE9" xmlns="http://www.w3.org/1999/xhtml"><![endif]-->
<!--[if !IE]><!--><html xmlns="http://www.w3.org/1999/xhtml"><!--<![endif]-->
```

However, the observed output is:
```html
<!--[if lt IE 9 ]&gt;&lt;html class="ltIE9" xmlns="http://www.w3.org/1999/xhtml"&gt;&lt;![endif]-->
<!--[if IE 9 ]&gt;&lt;html class="IE9" xmlns="http://www.w3.org/1999/xhtml"&gt;&lt;![endif]-->
<!--[if !IE]&gt;&lt;!--><html xmlns="http://www.w3.org/1999/xhtml"><!--&lt;![endif]-->
```

Based on the comments in HtmlResponseWriter#writeComment(), this appears to be a bug. Although, based on the workaround that @BalusC put together in OmniFaces, I'm assuming that there is something else preventing this behavior from being changed to match said comments?

See pull request #4289 for my proposed fix.

**Comment by BalusC** [comment]
IE conditional comments are an IE specific feature and not part of the HTML standard.

**Comment by Toberumono** [comment]
@BalusC While the IE conditional comments are an IE specific feature, they are presently broken because JSF's HtmlResponseWriter is improperly escaping the contents of comments. The HTML 5 standard, [section 12.1.6](https://html.spec.whatwg.org/multipage/syntax.html#comments) does not preclude '>' or '<' from appearing in comments. Actually, it explicitly states that `<!` is allowed at the end of comment strings. JSF encodes this to `&lt;!`, which is not in line with the specification (As a demonstration of this, `<!-- testing <!-->` is output to the page as `<!-- testing &lt;!-->`).

Given that, I would argue that this issue should be fixed. Also, the fix that I proposed in my pull request is not specific to IE conditional comments - it fixes character encoding in comments as a whole.
