### ISSUE TITLE
Make websocket bidirectional

### ISSUE THREAD

**Issue by muellermi** [javaserverfaces/mojarra#4356]
I suggest to add a "source" attribute to websocket

 <f:websocket channel="events" source="mySourceId" ...

If source is declared and it refers to an input element, then on every change (or blur?) event of that element it's content will be submitted to the server via the websocket channel.

Using an additional attribute "onSourceEvent" may specify a different event (e.g. key press) to trigger the sending.

**Comment by BalusC** [comment]
<f:websocket> is [purposefully](https://javaee.github.io/javaee-spec/javadocs/javax/faces/push/Push.html#usage-server) unidirectional as the other direction doesn't allow maintaining the view state and checking security constraints. For that you can keep using <f:ajax>.
